image:
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

install:
- pip install -r requirements.txt

build_script:
  - pyinstaller minimal.py --onefile --windowed -n coaro_decrypt

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
#
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a coaro_decrypt-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: coaro_decrypt-windows.zip

#
#   macOS package
#
-
  matrix:
    only:
    - image: macOS

  after_build:
  - ls
  - ls dist

  artifacts:
  - path: dist
  - path: dist/coaro_decrypt.app

#
#   Linux package
#
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf coaro_decrypt-linux.tar.gz -C dist

  artifacts:
  - path: coaro_decrypt-linux.tar.gz
