image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name coaro_decrypt --product-name coaro_decrypt --product-version "0.0.1"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
#
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a coaro_decrypt-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: coaro_decrypt-windows.zip

#
#   macOS package
#
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf coaro_decrypt-macos.tar.gz -C dist coaro_decrypt.app

  artifacts:
  - path: coaro_decrypt-macos.tar.gz

#
#   Linux package
#
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf coaro_decrypt-linux.tar.gz -C dist coaro_decrypt

  artifacts:
  - path: coaro_decrypt-linux.tar.gz
